name: Todo.ly
on:
  push:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install tools
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
      - name: Build
        run: dotnet build APITestingFramework/
      - name: Check format issues
        run: dotnet format --verify-no-changes -v d APITestingFramework/
      - name: Run tests
        run: dotnet test APITestingFramework/ --logger "trx;LogFileName=${{ github.run_number }}.trx"         

      - name: Create Livingdoc reports
        if: always()
        run: livingdoc feature-folder APITestingFramework/ -t APITestingFramework/ReportOutputs/TestExecution.json
      - name: Upload LivingDoc report file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Run#${{ github.run_number }}_LivingDoc.html
          path: LivingDoc.html
      - name: Upload .trx report file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Run#${{ github.run_number }}_report.trx
          path: APITestingFramework/TestResults/${{ github.run_number }}.trx