name: King of Tokyo

on:
  push:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install tools
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
      #- name: Restore tools
      #  run: dotnet tool restore --tool-manifest KOF/.config/dotnet-tools.json
      - name: Build
        run: dotnet build APITestingFramework/
      - name: Check format issues
        run: dotnet format --verify-no-changes -v d APITestingFramework/
      - name: Run tests
        #run: dotnet test APITestingFramework/ -l html --collect:"XPlat Code Coverage" --results-directory "TestResults-${{ matrix.dotnet-version }}"
        run: dotnet test APITestingFramework/

      - name: Create Livingdoc reports
        run: livingdoc feature-folder APITestingFramework/ -t APITestingFramework/ReportOutputs/TestExecution.json
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: LivingDoc.html
          path: LivingDoc.html
          #Use always() to always run this step to publish test results when there are test failures
        #if: ${{ always() }}
      #- name: Generate code coverage report
      #  run: cd KOF/; dotnet reportgenerator -reports:"../TestResults-${{ matrix.dotnet-version }}/**/*.cobertura.xml" -targetdir:".coveragereport"
      #- name: Upload code coverage report
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: code-coverage-${{ matrix.dotnet-version }}
      #    path: KOF/.coveragereport
        # Use always() to always run this step to publish test results when there are test failures
      #  if: ${{ always() }}